FROM python:3.14-alpine@sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92 AS builder
COPY --from=ghcr.io/astral-sh/uv:latest@sha256:d0a0a753ab981624b49c97abc98821c1c09f4ca69d1ef5cee69c501be3d88479 /uv /uvx /bin/

# Change the working directory to the `app` directory
WORKDIR /app

# Install dependencies in a cache layer. This speeds up build time
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=secret,id=nexus_username \
  --mount=type=secret,id=nexus_password \
  --mount=type=bind,source=uv.lock,target=uv.lock,Z \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml,Z \
  UV_INDEX_NEXUS_USERNAME="$(cat /run/secrets/nexus_username)" \
  UV_INDEX_NEXUS_PASSWORD="$(cat /run/secrets/nexus_password)" \
  uv sync --locked --no-install-project --no-editable

# Copy the project into the intermediate image
COPY . /app

# Sync the project and install it, now that we have access to the source code
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=secret,id=nexus_username \
  --mount=type=secret,id=nexus_password \
  UV_INDEX_NEXUS_USERNAME="$(cat /run/secrets/nexus_username)" \
  UV_INDEX_NEXUS_PASSWORD="$(cat /run/secrets/nexus_password)" \
  uv sync --locked --no-editable --no-dev

FROM python:3.14-alpine@sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92

# Create a non-root user and group with specific IDs
RUN addgroup -S -g 1000 app && adduser -S -u 1000 -G app app

# Copy the environment from builder
COPY --from=builder --chown=app:app /app/.venv /app/.venv

# Switch to the non-root user
USER app

# Expose the correct port
EXPOSE 22111

# Run the application using the compiled app command
CMD ["/app/.venv/bin/study-tracker-frontend"]
